# Generated by Django 2.1.7 on 2019-03-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0002_auto_20190307_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location_details',
            field=models.TextField(blank=True, help_text="How to find the meeting at the location, I.e.: 'In the basement', 'In the rear building.'", null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_details',
            field=models.TextField(blank=True, help_text='Additional details about the meeting.', null=True),
        ),
    ]
