# Generated by Django 2.2.9 on 2020-01-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0003_location_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_details',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location_details',
        ),
        migrations.AddField(
            model_name='location',
            name='details',
            field=models.TextField(blank=True, help_text="How to find the meeting at the location, I.e.: 'In the basement', 'In the rear building.'", null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='area',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='district',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
