# Generated by Django 2.2.9 on 2020-01-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0004_auto_20200110_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(default=1, limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='meeting_guide.Region'),
            preserve_default=False,
        ),
    ]
