# Generated by Django 2.2.11 on 2020-03-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0006_auto_20200313_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='payment_paypal',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='PayPal account'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='payment_venmo',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Venmo account'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_conference_dial_in',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meeting',
            name='video_conference_url',
            field=models.URLField(blank=True, default='', verbose_name='Video conference URL'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (3, 'Online Only'), (2, 'Suspended'), (0, 'Inactive Permanently')], default=1),
        ),
    ]
