# Generated by Django 2.2.5 on 2020-03-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0008_auto_20200321_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive Permanently')], default=1),
        ),
    ]
