# Generated by Django 2.2.12 on 2020-04-05 14:15

from django.db import migrations, models
import meeting_guide.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0011_auto_20200404_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='venmo',
            field=models.TextField(blank=True, default='', help_text='Example: @aa-tbc', max_length=31, validators=[meeting_guide.validators.VenmoUsernameValidator()], verbose_name='Venmo Account'),
        ),
    ]
