# Generated by Django 3.0.8 on 2020-07-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0012_auto_20200405_1015'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingtype',
            name='meeting_gui_meeting_e22f98_idx',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='video_conference_phone',
            new_name='conference_phone',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='video_conference_url',
            new_name='conference_url',
        ),
        migrations.RenameField(
            model_name='meetingtype',
            old_name='meeting_guide_code',
            new_name='spec_code',
        ),
        migrations.AddIndex(
            model_name='meetingtype',
            index=models.Index(fields=['spec_code'], name='meeting_gui_spec_co_dfdefe_idx'),
        ),
    ]
