# Generated by Django 3.0.8 on 2020-07-22 20:27

import django.core.validators
from django.db import migrations, models
import meeting_guide.validators


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0013_auto_20200722_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='conference_phone',
            field=models.CharField(blank=True, default='', help_text=('Enter a valid conference phone number. The three groups of numbers in this example are a Zoom phone number, meeting code, and password: +19294362866,,2151234215#,,#,,12341234#',), max_length=255, validators=[meeting_guide.validators.ConferencePhoneValidator()]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='paypal',
            field=models.TextField(blank=True, default='', help_text='Example: sepia-mygroup', max_length=255, validators=[meeting_guide.validators.PayPalUsernameValidator(), django.core.validators.MinLengthValidator(8)], verbose_name='PayPal Username'),
        ),
    ]
