# Generated by Django 3.2.8 on 2021-11-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_guide', '0015_auto_20211002_1711'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meeting',
            name='meeting_gui_meeting_792a4f_idx',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_location',
        ),
    ]
