# Generated by Django 4.2.5 on 2023-10-02 20:31

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("meeting_guide", "0015_auto_20211002_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="gso_number",
            field=models.CharField(
                blank=True,
                help_text="General Service Office (GSO) number, if applicable.",
                max_length=10,
                null=True,
                verbose_name="GSO Number",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="area",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
